# SERIAL
SERIAL_PORT = '/dev/ttyACM0'
SERIAL_BAUD_RATE = 9600
SERIAL_TIMEOUT = 2

# TELEGRAM
TELEGRAM_TOKEN = ''
TELEGRAM_CHAT_ID = ''
TELEGRAM_SIGHTING_MESSAGE = 'There is movement in the nest!'

# SIGHTINGS
RECENTLY_SIGHTING = 5 * 60  # Time in seconds
