on: [ push ]

name: Build backend images

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true
        run: poetry install --no-interaction --no-root
      - name: Pass tests
        run: |
          pytest -c pytest.ini --maxfail=5
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true
        run: poetry install --no-interaction --no-root
      - name: Pass tests
        run: |
          flake8
